twig:
    file_name_pattern: '*.twig'
    globals:
      utils: '@App\Twig\TwigUtils'
      rolemanager: '@App\Horaro\RoleManager'
      oauth_settings: '%oauth%'

when@test:
    twig:
        strict_variables: true
