# Never edit this file directly!
# Instead, copy it and name the copy 'parameters.yml'. Edit the copy only.

# Your database connection. Set the user, password and dbname. If needed, change
# the host.
database:
  driver:   pdo_mysql
  host:     127.0.0.1
  user:     yourusername
  password: yourpassword
  dbname:   yourdatabasename
  charset:  utf8
  driverOptions:
    1002: SET NAMES utf8

# Your secret.
# This is a random string of characters. Set it to anything you want, but make it
# at least 10 characters long and random. You cannot leave this field blank.
# Something like this is good: http://www.random.org/strings/?num=1&len=20&digits=on&upperalpha=on&loweralpha=on&format=plain
secret: ''

# Set this to false to enable production mode. This will:
#   - turn off Twig auto-reloads
#   - turn off on-demand generation of Doctrine proxies
#   - create links to versioned assets
# See the README.md for more details.
debug: true

# Directory where generated Doctrine proxies are stored. You can use either
# relative paths or absolute ones (on *nix systems).
doctrine_proxies: tmp/doctrine-proxies/

# If you change something in here, you have to adjust the schema.orm.yml and your
# database as well. Generally, there is no reason to touch this.
session:
  db_table:        sessions
  db_id_col:       id
  db_data_col:     data
  db_lifetime_col: lifetime
  db_time_col:     mtime
  lock_mode:       1 # advisory (transactional would break Horaro's own transactions)

# Cache times.
# These determine how long (in minutes) responses of certain kinds (schedules,
# events, calendar, ...) should be cached on intermediate proxies.
cache_ttls:
  schedule:  1
  event:    10
  homepage: 10
  calendar: 60
  other:    60

# Lifetime of session cookies in seconds.
cookie_lifetime: 86400

# This controls the `secure` flag on cookies. Set this to true when you operate
# Horaro only via SSL/TLS.
cookie_secure: false

# Set this to the number of seconds to use for the max-age value in the
# Strict-Transport-Security header. Use this only if you exclusively (!) offer
# Horaro via HTTPS and are sure that you can provide working HTTPS for
# however long you choose to set this.
hsts_max_age: ~

# OAuth configuration
# Set this if you want to allow people to log in via Twitch. If you want that,
# you will know what these settings mean.
# The redirect url is https://example.com/-/oauth/callback (replace example with your own domain)
oauth: []
#  twitch:
#    clientId:     ...
#    clientSecret: ...
