services:
  horaro:
    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:8000"
    volumes:
      - /coding/docker/mysql/horaro_parameters.yml:/var/www/horaro/config/parameters.yml:ro
    build:
      context: .
