parameters:
  horaro.roles: # the order is relevant here!
    - ROLE_GHOST
    - ROLE_USER
    - ROLE_ADMIN
    - ROLE_OP
  horaro.default_role: ROLE_USER
  horaro.languages:
    de_de: Deutsch
    en_us: English (US)
  horaro.themes:
    amelia: Amelia
    cerulean: Cerulean
    cosmo: Cosmo
    cyborg: Cyborg
    darkly: Darkly
    flatly: Flatly
    journal: Journal
    lumen: Lumen
    paper: Paper
    readable: Readable
    sandstone: Sandstone
    simplex: Simplex
    slate: Slate
    spacelab: Spacelab
    superhero: Superhero
    united: United
    yeti: Yeti
